### PR TITLE
Actualización general

### PR DESCRIPTION
**Pull request by abr4xas**
## Description

Actualización del paquete que incluye métodos para gestionar los pagos.

## Motivation and context

He estado trabajando con este paquete y necesitaba tener acceso a todos los demás puntos de consulta de instapago para cumplir otros requerimientos. 

## How has this been tested?

* php v7.0.15

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked.

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [ ] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by abr4xas** [comment]
Nota: Los test no funcionan porque al intentar correrlos me da el siguiente mensaje:

```
ReflectionException: Class config does not exist
```

Y no tengo idea de como hacerlo funcionar :sweat:

**Comment by kikemarto** [comment]
¡Hola! No realice las pruebas unitarias de la librería ya que la realice muy rápido para una tarea puntual. :(

**Comment by abr4xas** [comment]
@kikemarto no problem, igual podemos planificar y le buscamos solución a ese detalle :smiley: 

¿Usas telegram? Estoy por allá como @abr4xas :smile:

**Comment by kikemarto** [comment]
Ya te escribí

**Pull request merged**
